version: '3.9'
services:
  web:
    build: .
    ports:
      - '8000:8000'
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyACM0:/dev/ttyACM0" # https://dev.to/luckierdodge/how-to-communicate-with-an-arduino-from-docker-3fo7
      - "/dev/sda:/dev/xvda:rwm"
  #   volumes:
  #     - .:/code
  #   environment:
  #     - POSTGRES_NAME=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   depends_on:
  #     - db

  # db:
  #   image: postgres
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres


  # hivemq:
  #   container_name: hivemq-broker
  #   image: hivemq/hivemq4:latest
  #   # hostname: localhost
  #   ports:
  #     - "8080:8080"
  #     - "1883:1883"
    # environment:
    #   HIVEMQ_BIND_ADDRESS: "0.0.0.0"

