version: '3.9'
services:
  web:
    build:
      context: app
      target: builder
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  hivemq:
    container_name: hivemq-broker
    image: hivemq/hivemq4:latest
    # hostname: localhost
    ports:
      - "8080:8080"
      - "1883:1883"
    # environment:
    #   HIVEMQ_BIND_ADDRESS: "0.0.0.0"

